airports.data.path: "/Users/macbook/Documents/travelAud/optd-sample-20161201.csv"
users.data.path: "/Users/macbook/Documents/travelAud/sample_data.csv"
output.path: "/Users/macbook/Documents/travelAud/result.csv"
redis:
  host: "localhost"
  port: 6379

